<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

use App\Models\User;
use App\Models\Students;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
      //1
      $user = User::factory()->create([
         'name' => 'IMRA',
         'email' => 'imra_admin@darulhuffaz.com',
         'password' => bcrypt('1234567'),
         'type' => 'Headmaster',
      ]);

      //2
      $user = User::factory()->create([
         'name' => 'SYUKOR ',
         'email' => 'syukor_admin@darulhuffaz.com',
         'password' => bcrypt('1234567'),
         'type' => 'Headmaster',
     ]);

     //3
      $user = User::factory()->create([
         'name' => 'AHMAD',
         'email' => 'ahmad@gmail.com',
         'password' => bcrypt('ahmad123'),
         'type' => 'Parent',
     ]);

     //4
      $user = User::factory()->create([
         'name' => 'RAZAK',
         'email' => 'razak@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
      ]);

      //5
      $user = User::factory()->create([
         'name' => 'ZAIN ',
         'email' => 'zain@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
     ]);

     //6
      $user = User::factory()->create([
         'name' => 'DANISH',
         'email' => 'danish@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
      ]);

      //7
      $user = User::factory()->create([
         'name' => 'AMIN',
         'email' => 'amin@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
     ]);

     //8
      $user = User::factory()->create([
         'name' => 'SYAFIQ',
         'email' => 'syafiq@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
      ]);

      //9
      $user = User::factory()->create([
         'name' => 'ISMAIL',
         'email' => 'ismail@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
     ]);

     //10
      $user = User::factory()->create([
         'name' => 'HAFIZ',
         'email' => 'hafiz@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
      ]);

      //11
      $user = User::factory()->create([
         'name' => 'RAZALI',
         'email' => 'razali@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
     ]);

     //12
      $user = User::factory()->create([
         'name' => 'FIRDAUS',
         'email' => 'firdaus@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
      ]);

      //13
      $user = User::factory()->create([
         'name' => 'AMIR',
         'email' => 'amir@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
     ]);

     //14
      $user = User::factory()->create([
         'name' => 'HAKIM',
         'email' => 'hakim@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
      ]);

      //15
      $user = User::factory()->create([
         'name' => 'AZMAN',
         'email' => 'azman@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
     ]);

     //16
      $user = User::factory()->create([
         'name' => 'FAISAL',
         'email' => 'faisal@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
      ]);

      //17
      $user = User::factory()->create([
         'name' => 'MUHAMAD',
         'email' => 'muhamad@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
     ]);

     //18
     $user = User::factory()->create([
         'name' => 'AISHA',
         'email' => 'aisya@darulhuffaz.com',
         'password' => bcrypt('1234567'),
         'type' => 'Teacher',
     ]);

     //19
      $user = User::factory()->create([
         'name' => 'MOHAMMAD',
         'email' => 'mohammad@darulhuffaz.com',
         'password' => bcrypt('1234567'),
         'type' => 'Teacher',
      ]);

      //20
      $user = User::factory()->create([
         'name' => 'YUSUF',
         'email' => 'yusuf@darulhuffaz.com',
         'password' => bcrypt('1234567'),
         'type' => 'Teacher',
     ]);

     //21
      $user = User::factory()->create([
         'name' => 'SAFIYA',
         'email' => 'safiya@darulhuffaz.com',
         'password' => bcrypt('1234567'),
         'type' => 'Teacher',
      ]);

      //22
      $user = User::factory()->create([
         'name' => 'MARIAM',
         'email' => 'mariam@darulhuffaz.com',
         'password' => bcrypt('1234567'),
         'type' => 'Teacher',
     ]);

     //23
      $user = User::factory()->create([
         'name' => 'ZAKI',
         'email' => 'zaki@darulhuffaz.com',
         'password' => bcrypt('1234567'),
         'type' => 'Staff',
      ]);

      //24
      $user = User::factory()->create([
         'name' => 'FATIN',
         'email' => 'fatin@darulhuffaz.com',
         'password' => bcrypt('1234567'),
         'type' => 'Staff',
     ]);

     //25
      $user = User::factory()->create([
         'name' => 'FIKRI',
         'email' => 'ahmadfikri@darulhuffaz.com',
         'password' => bcrypt('1234567'),
         'type' => 'Staff',
      ]);

      //26
      $user = User::factory()->create([
         'name' => 'NURULAIN',
         'email' => 'nurulain@darulhuffaz.com',
         'password' => bcrypt('1234567'),
         'type' => 'Staff',
     ]);

     //27
      $user = User::factory()->create([
         'name' => 'ZULHELMI',
         'email' => 'zulhelmi@darulhuffaz.com',
         'password' => bcrypt('1234567'),
         'type' => 'Staff',
      ]);

      //28
      $user = User::factory()->create([
         'name' => 'ZAKIR',
         'email' => 'zakir@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
     ]);

     //29
      $user = User::factory()->create([
         'name' => 'NIK MAT',
         'email' => 'nikman@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
      ]);

      //30
      $user = User::factory()->create([
         'name' => 'ISMAIL ',
         'email' => 'ismail_hashim@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
     ]);

     //31
      $user = User::factory()->create([
         'name' => 'ZIZAN',
         'email' => 'zizan@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
     ]);

     //32
      $user = User::factory()->create([
         'name' => 'AMIN',
         'email' => 'amin.aman@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
      ]);

      //33
      $user = User::factory()->create([
         'name' => 'WAN AIMAN',
         'email' => 'wan.aiman@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
     ]);

     //34
      $user = User::factory()->create([
         'name' => 'ABDUL RAHIM',
         'email' => 'abdul.rahim@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
      ]);

      //35
      $user = User::factory()->create([
         'name' => 'HELMI',
         'email' => 'helmi@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
     ]);

     //36
      $user = User::factory()->create([
         'name' => 'AHMAD',
         'email' => 'ahmad.jamaludin@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
      ]);

      //37
      $user = User::factory()->create([
         'name' => 'AHMAD',
         'email' => 'ahmad.zulkefli@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
     ]);

     //38
      $user = User::factory()->create([
         'name' => 'MAT JUMAT',
         'email' => 'matjumat@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
      ]);

      //39
      $user = User::factory()->create([
         'name' => 'AHMAD',
         'email' => 'ahmad.ismail@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
     ]);

     //40
      $user = User::factory()->create([
         'name' => 'AHMAD',
         'email' => 'ahmad.jalal@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
      ]);

      //41
      $user = User::factory()->create([
         'name' => 'MOHD RAZALI',
         'email' => 'mohdrazali@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
     ]);

     //42
     $user = User::factory()->create([
         'name' => 'ABDULLAH',
         'email' => 'abdullah.mohammad@gmail.com',
         'password' => bcrypt('1234567'),
         'type' => 'Parent',
      ]);

      //43
      $user = User::factory()->create([
         'name' => 'SYAMSIAH',
         'email' => 'syamsiah@darulhuffaz.com',
         'password' => bcrypt('1234567'),
         'type' => 'Teacher',
      ]);

        Students::create([
           'Parent_id' => '15',
           'Class_id' => '5',
           'Staff_id' => '1',
           'FullName'  => 'MOHD AIMAN HAMDAN BIN RAZALI',
           'birthCertificateNO' => 'AN93834',
           'MyKid' => '060101-14-5678',
           'Address1' => 'No. 15, Jalan Bunga Raya',
           'Address2' => 'Taman Sri Permai',
           'Poscode' => '43200',
           'City' => 'Cheras',
           'State' => 'Selangor',
           'DOB' => '2009-06-22',
           'Sex' => 'Lelaki',
           'PhoneNo' => '011-11609038',
           'Nationality' => 'Warganegara',
           'Disability' => 'None',
           'BillSibling' => '5',
           'AnakKe' => '1',
           'SchoolName' => 'University Malaysia Terengganu',
           'Status' => 'Active',
           'LastPaymentDate' => '2023-02-01',
           'ParentFullName' => 'MOHD RAZALI BIN ABDUL RAHMAN',
           'ParentICno' => '700101-01-1234',
           'ParentAddress1' => 'No. 15, Jalan Bunga Raya',
           'ParentAddress2' => 'Taman Sri Permai',
           'ParentPoscode' => '43200',
           'ParentCity' => 'Cheras',
           'ParentState' => 'Selangor',
           'ParentPhoneNo' => '011-24798476',
           'ParentNationality' => 'Warganegara',
           'ParentJob' => 'Berniaga',
           'ParentIncome' => '1500.00',
           'OfficeAddress1' => 'No. 22, Jalan Teratai',
           'OfficeAddress2' => 'Taman Mawar',
           'OfficePoscode' => '56000',
           'OfficeCity' => 'Kuala Lumpur',
           'OfficeState' => 'Wilayah Persekutuan Kuala Lumpur',
           'RegistrastionFee' => 'paid',
         ]);

        Students::create([
            'Parent_id' => '7',
            'Class_id' => '3',
            'Staff_id' => '2',
            'FullName'  => 'ISKANDAR BIN ISMAIL',
            'birthCertificateNO' => 'AN93834',
            'MyKid' => '070201-08-9012',
            'Address1' => 'No. 8, Jalan Sengkurong',
            'Address2' => 'Taman Desa Jaya',
            'Poscode' => '46100',
            'City' => 'Petaling Jaya',
            'State' => 'Selangor',
            'DOB' => '2009-06-22',
            'Sex' => 'Lelaki',
            'PhoneNo' => '012-34567789',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '5',
            'AnakKe' => '1',
            'SchoolName' => 'University Malaysia Terengganu',
            'Status' => 'Active',
            'LastPaymentDate' => '2023-01-01',
            'ParentFullName' => 'ISMAIL BIN MOHAMAD RAZALI',
            'ParentICno' => '730512-07-2345',
            'ParentAddress1' => 'No. 15, Jalan Kiara',
            'ParentAddress2' => 'Mont Kiara',
            'ParentPoscode' => '50480',
            'ParentCity' => 'Kuala Lumpur',
            'ParentState' => 'Wilayah Persekutuan Kuala Lumpur',
            'ParentPhoneNo' => '011-24798476',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Berniaga',
            'ParentIncome' => '1500.00',
            'OfficeAddress1' => 'No. 15, Jalan Kiara',
            'OfficeAddress2' => 'Mont Kiara',
            'OfficePoscode' => '50480',
            'OfficeCity' => 'Kuala Lumpur',
            'OfficeState' => 'Wilayah Persekutuan Kuala Lumpur',
     'RegistrastionFee' => 'paid',         
         ]);

         Students::create([
            'Parent_id' => '4',
            'Class_id' => '3',
            'Staff_id' => '0',
            'FullName'  => 'AMRAN BIN MOHD DANISH',
            'birthCertificateNO' => 'AN93834',
            'MyKid' => '080301-12-3456',
            'Address1' => 'No. 5, Jalan Melati',
            'Address2' => 'Taman Bunga Raya',
            'Poscode' => '43200',
            'City' => 'Cheras',
            'State' => 'Selangor',
            'DOB' => '2009-06-22',
            'Sex' => 'Lelaki',
            'PhoneNo' => '011-11609038',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '5',
            'AnakKe' => '1',
            'SchoolName' => 'University Malaysia Terengganu',
            'Status' => 'Pending',
            'LastPaymentDate' => '2023-03-01',
            'ParentFullName' => 'MOHD DANISH BIN MOHD YUSOFF',
            'ParentICno' => '760303-10-3456',
            'ParentAddress1' => 'No. 5, Jalan Melati',
            'ParentAddress2' => 'Taman Bunga Raya',
            'ParentPoscode' => '43200',
            'ParentCity' => 'Cheras',
            'ParentState' => 'Selangor',
            'ParentPhoneNo' => '011-24798476',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Berniaga',
            'ParentIncome' => '1500.00',
            'OfficeAddress1' => 'No. 9, Jalan Cempaka',
            'OfficeAddress2' => 'Taman Cempaka',
            'OfficePoscode' => '43000',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
              'RegistrastionFee' => 'paid',
         ]);

         Students::create([
            'Parent_id' => '14',
            'Class_id' => '1',
            'Staff_id' => '1',
            'FullName'  => 'MOHD HAMDAN BIN ZULKEFLI',
            'birthCertificateNO' => 'AN93834',
            'MyKid' => '090401-04-7890',
            'Address1' => 'No. 12, Jalan Seri Indah',
            'Address2' => 'Taman Seri Alam',
            'Poscode' => '81750',
            'City' => 'Masai',
            'State' => 'Johor',
            'DOB' => '2009-06-22',
            'Sex' => 'Lelaki',
            'PhoneNo' => '011-11609038',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '5',
            'AnakKe' => '1',
            'SchoolName' => 'University Malaysia Terengganu',
            'Status' => 'Active',
            'LastPaymentDate' => '2023-05-01',
            'ParentFullName' => 'MOHD FAISAL BIN MOHD AZMAN',
            'ParentICno' => ' 790624-03-4567',
            'ParentAddress1' => 'No. 12, Jalan Seri Indah',
            'ParentAddress2' => 'Taman Seri Alam',
            'ParentPoscode' => '81750',
            'ParentCity' => 'Masai',
            'ParentState' => 'Johor',
            'ParentPhoneNo' => '011-24798476',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Berniaga',
            'ParentIncome' => '1500.00',
            'OfficeAddress1' => 'No. 7, Jalan Mawar',
            'OfficeAddress2' => 'Taman Sri Delima',
            'OfficePoscode' => '43100',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
              'RegistrastionFee' => 'paid',
         ]);

         Students::create([
            'Parent_id' => '2',
            'Class_id' => '5',
            'Staff_id' => '0',
            'FullName'  => 'MOHD HAZIQ BIN RAHMAN',
            'birthCertificateNO' => 'AN93834',
            'MyKid' => '100501-06-2345',
            'Address1' => 'No. 35, Jalan Dahlia',
            'Address2' => 'Taman Sri Wangi',
            'Poscode' => '71000',
            'City' => 'Port Dickson',
            'State' => 'Negeri Sembilan',
            'DOB' => '2009-06-22',
            'Sex' => 'Lelaki',
            'PhoneNo' => '011-11609038',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '5',
            'AnakKe' => '1',
            'SchoolName' => 'University Malaysia Terengganu',
            'Status' => 'Pending',
            'LastPaymentDate' => '2023-06-01',
            'ParentFullName' => 'ABDUL RAZAK BIN ABDUL RAHMAN',
            'ParentICno' => '820905-05-5678',
            'ParentAddress1' => 'No. 35, Jalan Dahlia',
            'ParentAddress2' => 'Taman Sri Wangi',
            'ParentPoscode' => '71000',
            'ParentCity' => 'Port Dickson',
            'ParentState' => 'Negeri Sembilan',
            'ParentPhoneNo' => '011-24798476',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Berniaga',
            'ParentIncome' => '1500.00',
            'OfficeAddress1' => 'No. 10, Jalan Bunga Raya',
            'OfficeAddress2' => 'Taman Bunga Indah',
            'OfficePoscode' => '78000',
            'OfficeCity' => 'Alor Setar',
            'OfficeState' => 'Kedah',
              'RegistrastionFee' => 'paid',
         ]);

         Students::create([
            'Parent_id' => '6',
            'Class_id' => '6',
            'Staff_id' => '5',
            'FullName'  => 'MOHD AIMAN HAMDAN BIN RAZALI',
            'birthCertificateNO' => 'AN93834',
            'MyKid' => '110601-10-6789',
            'Address1' => 'No. 14, Jalan Seroja',
            'Address2' => 'Taman Indah Permai',
            'Poscode' => '68000',
            'City' => 'Ampang',
            'State' => 'Selangor',
            'DOB' => '2009-06-22',
            'Sex' => 'Lelaki',
            'PhoneNo' => '011-11609038',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '5',
            'AnakKe' => '1',
            'SchoolName' => 'University Malaysia Terengganu',
            'Status' => 'Active',
            'LastPaymentDate' => '2023-04-01',
            'ParentFullName' => 'MOHD SYAFIQ BIN IBRAHIM',
            'ParentICno' => '850218-02-6789',
            'ParentAddress1' => 'No. 14, Jalan Seroja',
            'ParentAddress2' => 'Taman Indah Permai',
            'ParentPoscode' => '68000',
            'ParentCity' => 'Ampang',
            'ParentState' => 'Selangor',
            'ParentPhoneNo' => '011-24798476',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Berniaga',
            'ParentIncome' => '1500.00',
            'OfficeAddress1' => 'No. 18, Jalan Teratai',
            'OfficeAddress2' => 'Taman Mawar',
            'OfficePoscode' => '56000',
            'OfficeCity' => 'Kuala Lumpur',
            'OfficeState' => 'Wilayah Persekutuan Kuala Lumpur',
              'RegistrastionFee' => 'paid',
         ]);
 
         Students::create([
            'Parent_id' => '1',
            'Class_id' => '2',
            'Staff_id' => '4',
             'FullName'  => 'MOHD IMRAN BIN YUSOF',
             'birthCertificateNO' => 'AN93834',
             'MyKid' => '120701-02-0123',
             'Address1' => 'No. 23, Jalan Harmoni',
             'Address2' => 'Taman Seri Harmoni',
             'Poscode' => '43200',
             'City' => 'Cheras',
             'State' => 'Selangor',
             'DOB' => '2009-06-22',
             'Sex' => 'Lelaki',
             'PhoneNo' => '011-11609038',
             'Nationality' => 'Warganegara',
             'Disability' => 'None',
             'BillSibling' => '5',
             'AnakKe' => '1',
             'SchoolName' => 'University Malaysia Terengganu',
             'Status' => 'Active',
             'LastPaymentDate' => '2023-04-01',
             'ParentFullName' => 'AHMAD BIN ABDULLAH',
             'ParentICno' => '870409-08-7890',
             'ParentAddress1' => 'No. 23, Jalan Harmoni',
             'ParentAddress2' => 'Taman Seri Harmoni',
             'ParentPoscode' => '43200',
             'ParentCity' => 'Cheras',
             'ParentState' => 'Selangor',
             'ParentPhoneNo' => '011-24798476',
             'ParentNationality' => 'Warganegara',
             'ParentJob' => 'Berniaga',
             'ParentIncome' => '1500.00',
             'OfficeAddress1' => 'No. 35, Jalan Seri Murni',
             'OfficeAddress2' => 'Taman Sri Cendana',
             'OfficePoscode' => '43000',
             'OfficeCity' => '43000',
             'OfficeState' => 'Selangor',
              'RegistrastionFee' => 'paid',
            ]);
 
          Students::create([
             'Parent_id' => '5',
             'Class_id' => '2',
            'Staff_id' => '0',
             'FullName'  => 'MOHD AIDEL IMAN BIN ROSLI',
             'birthCertificateNO' => 'AN93834',
             'MyKid' => '130801-16-4567',
             'Address1' => 'No. 6, Jalan Cempaka',
             'Address2' => 'Taman Cempaka',
             'Poscode' => '43000',
             'City' => 'Kajang',
             'State' => 'Selangor',
             'DOB' => '2009-06-22',
             'Sex' => 'Lelaki',
             'PhoneNo' => '011-11609038',
             'Nationality' => 'Warganegara',
             'Disability' => 'None',
             'BillSibling' => '5',
             'AnakKe' => '1',
             'SchoolName' => 'University Malaysia Terengganu',
             'Status' => 'Pending',
             'LastPaymentDate' => '2023-06-01',
             'ParentFullName' => 'MOHD AMIN BIN ABDUL LATIF',
             'ParentICno' => '890710-11-8901',
             'ParentAddress1' => 'No. 6, Jalan Cempaka',
             'ParentAddress2' => 'Taman Cempaka',
             'ParentPoscode' => '43000',
             'ParentCity' => 'Kajang',
             'ParentState' => 'Selangor',
             'ParentPhoneNo' => '011-24798476',
             'ParentNationality' => 'Warganegara',
             'ParentJob' => 'Berniaga',
             'ParentIncome' => '1500.00',
             'OfficeAddress1' => 'No. 17, Jalan Teratai',
             'OfficeAddress2' => 'Taman Mawar',
             'OfficePoscode' => '56000',
             'OfficeCity' => 'Kuala Lumpur',
             'OfficeState' => 'Wilayah Persekutuan Kuala Lumpur  ',
              'RegistrastionFee' => 'paid',
            ]);
 
          Students::create([
             'Parent_id' => '3',
             'Class_id' => '12',
           'Staff_id' => '4',
             'FullName'  => 'MOHD HAMDAN BIN ZULKEFLI',
             'birthCertificateNO' => 'AN93834',
             'MyKid' => '140901-18-8901',
             'Address1' => 'No. 11, Jalan Melor',
             'Address2' => 'Taman Sri Melati',
             'Poscode' => '78000',
             'City' => 'Alor Setar',
             'State' => 'Kedah',
             'DOB' => '2009-06-22',
             'Sex' => 'Lelaki',
             'PhoneNo' => '011-11609038',
             'Nationality' => 'Warganegara',
             'Disability' => 'None',
             'BillSibling' => '5',
             'AnakKe' => '1',
             'SchoolName' => 'University Malaysia Terengganu',
             'Status' => 'Active',
             'LastPaymentDate' => '2023-02-01',
             'ParentFullName' => 'MOHD ZAIN BIN MOHAMAD',
             'ParentICno' => '720221-06-9012',
             'ParentAddress1' => 'No. 11, Jalan Melor',
             'ParentAddress2' => 'Taman Sri Melati',
             'ParentPoscode' => '78000',
             'ParentCity' => 'Alor Setar',
             'ParentState' => 'Kedah',
             'ParentPhoneNo' => '011-24798476',
             'ParentNationality' => 'Warganegara',
             'ParentJob' => 'Berniaga',
             'ParentIncome' => '1500.00',
             'OfficeAddress1' => 'No. 5, Jalan Seri Indah',
             'OfficeAddress2' => 'Taman Seri Alam',
             'OfficePoscode' => '81750',
             'OfficeCity' => 'Masai',
             'OfficeState' => 'Johor',
              'RegistrastionFee' => 'paid',
            ]);
 
          Students::create([
             'Parent_id' => '13',
             'Class_id' => '11',
           'Staff_id' => '3',
             'FullName'  => 'MOHD HAZIQ BIN AZMAN',
             'birthCertificateNO' => 'AN93834',
             'MyKid' => '151001-20-2345',
             'Address1' => 'No. 19, Jalan Bunga Raya',
             'Address2' => 'Taman Bunga Indah',
             'Poscode' => '78000',
             'City' => 'Alor Setar',
             'State' => 'Kedah',
             'DOB' => '2009-06-22',
             'Sex' => 'Lelaki',
             'PhoneNo' => '011-11609038',
             'Nationality' => 'Warganegara',
             'Disability' => 'None',
             'BillSibling' => '5',
             'AnakKe' => '1',
             'SchoolName' => 'University Malaysia Terengganu',
             'Status' => 'Active',
             'LastPaymentDate' => '2023-03-01',
             'ParentFullName' => 'AZMAN BIN HAMID',
             'ParentICno' => '750604-09-0123',
             'ParentAddress1' => 'No. 19, Jalan Bunga Raya',
             'ParentAddress2' => 'Taman Bunga Indah',
             'ParentPoscode' => '78000',
             'ParentCity' => 'Alor Setar',
             'ParentState' => 'Kedah',
             'ParentPhoneNo' => '011-24798476',
             'ParentNationality' => 'Warganegara',
             'ParentJob' => 'Berniaga',
             'ParentIncome' => '1500.00',
             'OfficeAddress1' => 'No. 6, Jalan Sengkurong',
             'OfficeAddress2' => 'Taman Desa Jaya',
             'OfficePoscode' => '46100',
             'OfficeCity' => 'Petaling Jaya',
             'OfficeState' => 'Selangor',
              'RegistrastionFee' => 'paid',
            ]);

          Students::create([
            'Parent_id' => '12',
            'Class_id' => '4',
           'Staff_id' => '4',
            'FullName'  => 'MOHD AIMAN HAMDAN BIN ABDUL HAKIM',
            'birthCertificateNO' => 'AN93834',
            'MyKid' => '161101-22-6789',
            'Address1' => 'No. 29, Jalan Seri Alam',
            'Address2' => 'Taman Seri Jaya',
            'Poscode' => '81750',
            'City' => 'Masai',
            'State' => 'Johor',
            'DOB' => '2009-06-22',
            'Sex' => 'Lelaki',
            'PhoneNo' => '011-11609038',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '5',
            'AnakKe' => '1',
            'SchoolName' => 'University Malaysia Terengganu',
            'Status' => 'Active',
            'LastPaymentDate' => '2023-04-01',
            'ParentFullName' => 'ABDUL HAKIM BIN MOHD YUSOF',
            'ParentICno' => '780815-12-1234',
            'ParentAddress1' => 'No. 29, Jalan Seri Alam',
            'ParentAddress2' => 'Taman Seri Jaya',
            'ParentPoscode' => '81750',
            'ParentCity' => 'Masai',
            'ParentState' => 'Johor',
            'ParentPhoneNo' => '011-24798476',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Berniaga',
            'ParentIncome' => '1500.00',
            'OfficeAddress1' => 'No. 12, Jalan Seri Indah',
            'OfficeAddress2' => 'Taman Seri Alam',
            'OfficePoscode' => '81750',
            'OfficeCity' => 'Masai',
            'OfficeState' => 'Johor',
              'RegistrastionFee' => 'paid',
         ]);
 
         Students::create([
             'Parent_id' => '10',
             'Class_id' => '1',
           'Staff_id' => '1',
             'FullName'  => 'MOHD IMRAN BIN MOHD FIRDAUS',
             'birthCertificateNO' => 'AN93834',
             'MyKid' => '171201-24-0123',
             'Address1' => 'No. 16, Jalan Dahlia',
             'Address2' => 'Taman Sri Wangi',
             'Poscode' => '71000',
             'City' => 'Port Dickson',
             'State' => 'Negeri Sembilan',
             'DOB' => '2009-06-22',
             'Sex' => 'Lelaki',
             'PhoneNo' => '011-11609038',
             'Nationality' => 'Warganegara',
             'Disability' => 'None',
             'BillSibling' => '5',
             'AnakKe' => '1',
             'SchoolName' => 'University Malaysia Terengganu',
             'Status' => 'Rejected',
             'LastPaymentDate' => '2023-02-01',
             'ParentFullName' => 'MOHD FIRDAUS BIN AHMAD',
             'ParentICno' => '800126-04-2345',
             'ParentAddress1' => 'No. 16, Jalan Dahlia',
             'ParentAddress2' => 'Taman Sri Wangi',
             'ParentPoscode' => '71000',
             'ParentCity' => 'Port Dickson',
             'ParentState' => 'Negeri Sembilan',
             'ParentPhoneNo' => '011-24798476',
             'ParentNationality' => 'Warganegara',
             'ParentJob' => 'Berniaga',
             'ParentIncome' => '1500.00',
             'OfficeAddress1' => 'No. 23, Jalan Harmoni',
             'OfficeAddress2' => 'Taman Seri Harmoni',
             'OfficePoscode' => '43200',
             'OfficeCity' => 'Cheras',
             'OfficeState' => 'Selangor',
              'RegistrastionFee' => 'paid',
            ]);
 
          Students::create([
             'Parent_id' => '8',
             'Class_id' => '6',
           'Staff_id' => '3',
             'FullName'  => 'MOHD AIDEL IMAN BIN HAFIZ',
             'birthCertificateNO' => 'AN93834',
             'MyKid' => '181301-26-4567',
             'Address1' => 'No. 30, Jalan Teratai',
             'Address2' => 'Taman Mawar',
             'Poscode' => '56000',
             'City' => 'Kuala Lumpur',
             'State' => 'Wilayah Persekutuan Kuala Lumpur',
             'DOB' => '2009-06-22',
             'Sex' => 'Lelaki',
             'PhoneNo' => '011-11609038',
             'Nationality' => 'Warganegara',
             'Disability' => 'None',
             'BillSibling' => '5',
             'AnakKe' => '1',
             'SchoolName' => 'University Malaysia Terengganu',
             'Status' => 'Active',
             'LastPaymentDate' => '2023-05-01',
             'ParentFullName' => 'HAFIZ BIN ZULKIFLI',
             'ParentICno' => '830407-07-3456',
             'ParentAddress1' => 'No. 30, Jalan Teratai',
             'ParentAddress2' => 'Taman Mawar',
             'ParentPoscode' => '56000',
             'ParentCity' => 'Kuala Lumpur',
             'ParentState' => 'Wilayah Persekutuan Kuala Lumpur',
             'ParentPhoneNo' => '011-24798476',
             'ParentNationality' => 'Warganegara',
             'ParentJob' => 'Berniaga',
             'ParentIncome' => '1500.00',
             'OfficeAddress1' => 'No. 11, Jalan Melor',
             'OfficeAddress2' => 'Taman Sri Melati',
             'OfficePoscode' => '78000',
             'OfficeCity' => 'Alor Setar',
             'OfficeState' => 'Kedah',
              'RegistrastionFee' => 'paid',
            ]);
 
          Students::create([
             'Parent_id' => '11',
             'Class_id' => '11',
           'Staff_id' => '5',
             'FullName'  => 'MOHD HAMDAN BIN MOHD AMIR',
             'birthCertificateNO' => 'AN93834',
             'MyKid' => '191401-28-8901',
             'Address1' => 'No. 7, Jalan Sri Permai',
             'Address2' => 'Taman Sri Perindu',
             'Poscode' => '31400',
             'City' => 'Ipoh',
             'State' => 'Perak',
             'DOB' => '2009-06-22',
             'Sex' => 'Lelaki',
             'PhoneNo' => '011-11609038',
             'Nationality' => 'Warganegara',
             'Disability' => 'None',
             'BillSibling' => '5',
             'AnakKe' => '1',
             'SchoolName' => 'University Malaysia Terengganu',
             'Status' => 'Active',
             'LastPaymentDate' => '2023-04-01',
             'ParentFullName' => 'MOHD AMIR BIN ISKANDAR',
             'ParentICno' => '860820-01-4567',
             'ParentAddress1' => 'No. 7, Jalan Sri Permai',
             'ParentAddress2' => 'Taman Sri Perindu',
             'ParentPoscode' => '31400',
             'ParentCity' => 'Ipoh',
             'ParentState' => 'Perak',
             'ParentPhoneNo' => '011-24798476',
             'ParentNationality' => 'Warganegara',
             'ParentJob' => 'Berniaga',
             'ParentIncome' => '1500.00',
             'OfficeAddress1' => 'No. 14, Jalan Teratai',
             'OfficeAddress2' => 'Taman Mawar',
             'OfficePoscode' => '56000',
             'OfficeCity' => 'Kuala Lumpur',
             'OfficeState' => 'Wilayah Persekutuan Kuala Lumpur',
              'RegistrastionFee' => 'paid',
            ]);
 
          Students::create([
             'Parent_id' => '9',
             'Class_id' => '12',
             'Staff_id' => '4',
             'FullName'  => 'MOHD HAZIQ BIN MOHD RAZALI',
             'birthCertificateNO' => 'AN93834',
             'MyKid' => '201501-30-2345',
             'Address1' => 'No. 21, Jalan Delima',
             'Address2' => 'Taman Seri Delima',
             'Poscode' => '83000',
             'City' => 'Batu Pahat',
             'State' => 'Johor',
             'DOB' => '2009-06-22',
             'Sex' => 'Lelaki',
             'PhoneNo' => '011-11609038',
             'Nationality' => 'Warganegara',
             'Disability' => 'None',
             'BillSibling' => '5',
             'AnakKe' => '1',
             'SchoolName' => 'University Malaysia Terengganu',
             'Status' => 'Rejected',
             'LastPaymentDate' => '2023-04-01',
             'ParentFullName' => 'MOHD RAZALI BIN ABDUL RAHMAN',
             'ParentICno' => '880301-03-5678',
             'ParentAddress1' => 'No. 21, Jalan Delima',
             'ParentAddress2' => 'Taman Seri Delima',
             'ParentPoscode' => '83000',
             'ParentCity' => 'Batu Pahat',
             'ParentState' => 'Johor',
             'ParentPhoneNo' => '011-24798476',
             'ParentNationality' => 'Warganegara',
             'ParentJob' => 'Berniaga',
             'ParentIncome' => '1500.00',
             'OfficeAddress1' => 'No. 25, Jalan Cempaka',
             'OfficeAddress2' => 'Taman Cempaka',
             'OfficePoscode' => '43000',
             'OfficeCity' => 'Kajang',
             'OfficeState' => 'Selangor',
              'RegistrastionFee' => 'paid',
            ]);

         //  ----------------------------------------------------------
          Students::create([
            'Parent_id' => '16',
            'Class_id' => '10',
            'Staff_id' => '4',
            'FullName' => 'NURUL AMIRA BINTI ABDULLAH',
            'birthCertificateNO' => 'AB12943',
            'MyKid' => '201607-14-5678',
            'Address1' => 'No. 8, Jalan Harmoni',
            'Address2' => 'Taman Seri Harmoni',
            'Poscode' => '43200',
            'City' => 'Cheras',
            'State' => 'Selangor',
            'DOB' => '2008-03-11',
            'Sex' => 'Perempuan',
            'PhoneNo' => '012-3456789',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '2',
            'AnakKe' => '3',
            'SchoolName' => 'SMK Taman Seri',
            'Status' => 'Active',
            'LastPaymentDate' => '2023-01-15',
            'ParentFullName' => 'ABDULLAH BIN MOHAMMAD',
            'ParentICno' => '760501-07-8901',
            'ParentAddress1' => 'No. 8, Jalan Harmoni',
            'ParentAddress2' => 'Taman Seri Harmoni',
            'ParentPoscode' => '43200',
            'ParentCity' => 'Cheras',
            'ParentState' => 'Selangor',
            'ParentPhoneNo' => '019-8765432',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Kakitangan Kerajaan',
            'ParentIncome' => '5000.00',
            'OfficeAddress1' => 'No. 18, Jalan Anggerik',
            'OfficeAddress2' => 'Taman Anggerik',
            'OfficePoscode' => '43020',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
              'RegistrastionFee' => 'paid',
         ]);
            
            Students::create([
            'Parent_id' => '29',
            'Class_id' => '4',
            'Staff_id' => '2',
            'FullName' => 'NIK MAT BIN NIK MAT',
            'birthCertificateNO' => 'CD23561',
            'MyKid' => '201403-21-1234',
            'Address1' => 'No. 7, Jalan Seri Baiduri',
            'Address2' => 'Taman Seri Baiduri',
            'Poscode' => '83020',
            'City' => 'Johor Bahru',
            'State' => 'Johor',
            'DOB' => '2007-09-03',
            'Sex' => 'Lelaki',
            'PhoneNo' => '011-23456789',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '1',
            'AnakKe' => '2',
            'SchoolName' => 'SMK Taman Perindustrian',
            'Status' => 'Active',
            'LastPaymentDate' => '2023-02-10',
            'ParentFullName' => 'NIK MAT BIN NIK AZIZ',
            'ParentICno' => '790821-08-4321',
            'ParentAddress1' => 'No. 7, Jalan Seri Baiduri',
            'ParentAddress2' => 'Taman Seri Baiduri',
            'ParentPoscode' => '83020',
            'ParentCity' => 'Johor Bahru',
            'ParentState' => 'Johor',
            'ParentPhoneNo' => '019-7654321',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Pegawai Bank',
            'ParentIncome' => '8000.00',
            'OfficeAddress1' => 'No. 10, Jalan Indah',
            'OfficeAddress2' => 'Taman Indah',
            'OfficePoscode' => '83000',
            'OfficeCity' => 'Johor Bahru',
            'OfficeState' => 'Johor',
                 'RegistrastionFee' => 'paid',
         ]);
            
            Students::create([
            'Parent_id' => '22',
            'Class_id' => '8',
            'Staff_id' => '5',
            'FullName' => 'SITI ZAINAB BINTI AHMAD',
            'birthCertificateNO' => 'FG17652',
            'MyKid' => '201001-13-6789',
            'Address1' => 'No. 14, Jalan Megah',
            'Address2' => 'Taman Megah Indah',
            'Poscode' => '75400',
            'City' => 'Melaka',
            'State' => 'Melaka',
            'DOB' => '2009-08-22',
            'Sex' => 'Perempuan',
            'PhoneNo' => '017-9876543',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '3',
            'AnakKe' => '1',
            'SchoolName' => 'SMK Perkampungan Jaya',
            'Status' => 'Pending',
            'LastPaymentDate' => '2023-04-20',
            'ParentFullName' => 'AHMAD BIN JAMALUDIN',
            'ParentICno' => '820612-05-4321',
            'ParentAddress1' => 'No. 14, Jalan Megah',
            'ParentAddress2' => 'Taman Megah Indah',
            'ParentPoscode' => '75400',
            'ParentCity' => 'Melaka',
            'ParentState' => 'Melaka',
            'ParentPhoneNo' => '016-8765432',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Juruteknik',
            'ParentIncome' => '3500.00',
            'OfficeAddress1' => 'No. 20, Jalan Bunga Raya',
            'OfficeAddress2' => 'Taman Bunga Raya',
            'OfficePoscode' => '75000',
            'OfficeCity' => 'Melaka',
            'OfficeState' => 'Melaka',
                 'RegistrastionFee' => 'paid',
         ]);
            
            Students::create([
            'Parent_id' => '23',
            'Class_id' => '7',
            'Staff_id' => '1',
            'FullName' => 'LUQMAN BIN HELMI',
            'birthCertificateNO' => 'EF87321',
            'MyKid' => '201104-10-4321',
            'Address1' => 'No. 3, Jalan Bahagia',
            'Address2' => 'Taman Bahagia',
            'Poscode' => '56000',
            'City' => 'Kuala Lumpur',
            'State' => 'Wilayah Persekutuan',
            'DOB' => '2011-03-18',
            'Sex' => 'Lelaki',
            'PhoneNo' => '016-7654321',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '2',
            'AnakKe' => '2',
            'SchoolName' => 'SK Seri Wangsa',
            'Status' => 'Active',
            'LastPaymentDate' => '2023-01-05',
            'ParentFullName' => 'HELMI BIN HAIRUL',
            'ParentICno' => '840501-07-1234',
            'ParentAddress1' => 'No. 3, Jalan Bahagia',
            'ParentAddress2' => 'Taman Bahagia',
            'ParentPoscode' => '56000',
            'ParentCity' => 'Kuala Lumpur',
            'ParentState' => 'Wilayah Persekutuan',
            'ParentPhoneNo' => '019-9876543',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Pegawai Kerajaan',
            'ParentIncome' => '6000.00',
            'OfficeAddress1' => 'No. 5, Jalan Angsana',
            'OfficeAddress2' => 'Taman Angsana',
            'OfficePoscode' => '56100',
            'OfficeCity' => 'Kuala Lumpur',
            'OfficeState' => 'Wilayah Persekutuan',
                 'RegistrastionFee' => 'paid',
         ]);
            
            Students::create([
            'Parent_id' => '24',
            'Class_id' => '9',
            'Staff_id' => '3',
            'FullName' => 'NURUL AZIRA BINTI ABDUL RAHIM',
            'birthCertificateNO' => 'GH34678',
            'MyKid' => '201209-25-7890',
            'Address1' => 'No. 12, Jalan Bestari',
            'Address2' => 'Taman Bestari',
            'Poscode' => '43300',
            'City' => 'Seri Kembangan',
            'State' => 'Selangor',
            'DOB' => '2012-04-15',
            'Sex' => 'Perempuan',
            'PhoneNo' => '019-8765432',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '4',
            'AnakKe' => '3',
            'SchoolName' => 'SK Taman Seri',
            'Status' => 'Pending',
            'LastPaymentDate' => '2023-03-30',
            'ParentFullName' => 'ABDUL RAHIM BIN HASHIM',
            'ParentICno' => '850701-03-4567',
            'ParentAddress1' => 'No. 12, Jalan Bestari',
            'ParentAddress2' => 'Taman Bestari',
            'ParentPoscode' => '43300',
            'ParentCity' => 'Seri Kembangan',
            'ParentState' => 'Selangor',
            'ParentPhoneNo' => '012-3456789',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Pengurus Perniagaan',
            'ParentIncome' => '4500.00',
            'OfficeAddress1' => 'No. 15, Jalan Mawar',
            'OfficeAddress2' => 'Taman Mawar',
            'OfficePoscode' => '43200',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
                 'RegistrastionFee' => 'paid',
         ]);
            
            Students::create([
            'Parent_id' => '25',
            'Class_id' => '7',
            'Staff_id' => '1',
            'FullName' => 'WAN NOR ALYA BINTI WAN AIMAN',
            'birthCertificateNO' => 'IJ98675',
            'MyKid' => '201506-05-4321',
            'Address1' => 'No. 5, Jalan Ceria',
            'Address2' => 'Taman Ceria',
            'Poscode' => '81200',
            'City' => 'Johor Bahru',
            'State' => 'Johor',
            'DOB' => '2015-10-20',
            'Sex' => 'Perempuan',
            'PhoneNo' => '011-98765432',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '3',
            'AnakKe' => '1',
            'SchoolName' => 'SK Taman Seri',
            'Status' => 'Active',
            'LastPaymentDate' => '2023-04-08',
            'ParentFullName' => 'WAN AIMAN BIN WAN ZOL',
            'ParentICno' => '800710-03-1234',
            'ParentAddress1' => 'No. 5, Jalan Ceria',
            'ParentAddress2' => 'Taman Ceria',
            'ParentPoscode' => '81200',
            'ParentCity' => 'Johor Bahru',
            'ParentState' => 'Johor',
            'ParentPhoneNo' => '019-8765432',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Juruteknik',
            'ParentIncome' => '3800.00',
            'OfficeAddress1' => 'No. 7, Jalan Bakti',
            'OfficeAddress2' => 'Taman Bakti',
            'OfficePoscode' => '81100',
            'OfficeCity' => 'Johor Bahru',
            'OfficeState' => 'Johor',
                 'RegistrastionFee' => 'paid',
         ]);
            
            Students::create([
            'Parent_id' => '26',
            'Class_id' => '10',
            'Staff_id' => '2',
            'FullName' => 'ALISYA MAISARAH BINTI AMIN',
            'birthCertificateNO' => 'KL53698',
            'MyKid' => '201312-10-5678',
            'Address1' => 'No. 9, Jalan Harmoni',
            'Address2' => 'Taman Harmoni Indah',
            'Poscode' => '43300',
            'City' => 'Seri Kembangan',
            'State' => 'Selangor',
            'DOB' => '2013-09-15',
            'Sex' => 'Perempuan',
            'PhoneNo' => '016-8765432',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '4',
            'AnakKe' => '2',
            'SchoolName' => 'SK Taman Seri',
            'Status' => 'Rejected',
            'LastPaymentDate' => '2023-02-25',
            'ParentFullName' => 'AMIN BIN AMAN',
            'ParentICno' => '811005-07-4321',
            'ParentAddress1' => 'No. 9, Jalan Harmoni',
            'ParentAddress2' => 'Taman Harmoni Indah',
            'ParentPoscode' => '43300',
            'ParentCity' => 'Seri Kembangan',
            'ParentState' => 'Selangor',
            'ParentPhoneNo' => '019-9876543',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Pegawai Bank',
            'ParentIncome' => '5800.00',
            'OfficeAddress1' => 'No. 11, Jalan Murni',
            'OfficeAddress2' => 'Taman Murni',
            'OfficePoscode' => '43000',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
                 'RegistrastionFee' => 'paid',
         ]);
            
            Students::create([
            'Parent_id' => '27',
            'Class_id' => '9',
            'Staff_id' => '4',
            'FullName' => 'NURUL SYAFIQAH BINTI AHMAD',
            'birthCertificateNO' => 'AD26789',
            'MyKid' => '200905-15-9876',
            'Address1' => 'No. 18, Jalan Indah',
            'Address2' => 'Taman Indah',
            'Poscode' => '43200',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'DOB' => '2009-01-30',
            'Sex' => 'Perempuan',
            'PhoneNo' => '017-8765432',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '2',
            'AnakKe' => '1',
            'SchoolName' => 'SK Taman Kajang',
            'Status' => 'Active',
            'LastPaymentDate' => '2023-04-10',
            'ParentFullName' => 'ZIZAN BIN AMRAN',
            'ParentICno' => '811005-07-4321',
            'ParentAddress1' => 'No. 9, Jalan Harmoni',
            'ParentAddress2' => 'Taman Harmoni Indah',
            'ParentPoscode' => '43300',
            'ParentCity' => 'Seri Kembangan',
            'ParentState' => 'Selangor',
            'ParentPhoneNo' => '019-9876543',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Pegawai Bank',
            'ParentIncome' => '5800.00',
            'OfficeAddress1' => 'No. 11, Jalan Murni',
            'OfficeAddress2' => 'Taman Murni',
            'OfficePoscode' => '43000',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
                 'RegistrastionFee' => 'paid',
         ]);
            
            Students::create([
            'Parent_id' => '28',
            'Class_id' => '8',
            'Staff_id' => '3',
            'FullName' => 'AHMAD HAZIQ BIN ISMAIL',
            'birthCertificateNO' => 'PO34678',
            'MyKid' => '201109-20-7890',
            'Address1' => 'No. 2, Jalan Anggerik',
            'Address2' => 'Taman Anggerik',
            'Poscode' => '81200',
            'City' => 'Johor Bahru',
            'State' => 'Johor',
            'DOB' => '2011-06-05',
            'Sex' => 'Lelaki',
            'PhoneNo' => '019-7654321',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '3',
            'AnakKe' => '2',
            'SchoolName' => 'SK Taman Seri',
            'Status' => 'Pending',
            'LastPaymentDate' => '2023-01-02',
            'ParentFullName' => 'ISMAIL BIN HASHIM',
            'ParentICno' => '860602-03-4567',
            'ParentAddress1' => 'No. 2, Jalan Anggerik',
            'ParentAddress2' => 'Taman Anggerik',
            'ParentPoscode' => '81200',
            'ParentCity' => 'Johor Bahru',
            'ParentState' => 'Johor',
            'ParentPhoneNo' => '012-3456789',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Pegawai Kerajaan',
            'ParentIncome' => '4800.00',
            'OfficeAddress1' => 'No. 4, Jalan Mawar',
            'OfficeAddress2' => 'Taman Mawar',
            'OfficePoscode' => '81100',
            'OfficeCity' => 'Johor Bahru',
            'OfficeState' => 'Johor',
                 'RegistrastionFee' => 'paid',
         ]);

            Students::create([
            'Parent_id' => '17',
            'Class_id' => '6',
            'Staff_id' => '4',
            'FullName' => 'MOHD HAZIQ BIN MOHD RAZALI',
            'birthCertificateNO' => 'AN93834',
            'MyKid' => '201501-30-2345',
            'Address1' => 'No. 21, Jalan Delima',
            'Address2' => 'Taman Seri Delima',
            'Poscode' => '83000',
            'City' => 'Batu Pahat',
            'State' => 'Johor',
            'DOB' => '2009-06-22',
            'Sex' => 'Lelaki',
            'PhoneNo' => '011-11609038',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '5',
            'AnakKe' => '1',
            'SchoolName' => 'University Malaysia Terengganu',
            'Status' => 'Rejected',
            'LastPaymentDate' => '2023-04-01',
            'ParentFullName' => 'MOHD RAZALI BIN ABDUL RAHMAN',
            'ParentICno' => '880301-03-5678',
            'ParentAddress1' => 'No. 21, Jalan Delima',
            'ParentAddress2' => 'Taman Seri Delima',
            'ParentPoscode' => '83000',
            'ParentCity' => 'Batu Pahat',
            'ParentState' => 'Johor',
            'ParentPhoneNo' => '011-24798476',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Berniaga',
            'ParentIncome' => '1500.00',
            'OfficeAddress1' => 'No. 25, Jalan Cempaka',
            'OfficeAddress2' => 'Taman Cempaka',
            'OfficePoscode' => '43000',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
                 'RegistrastionFee' => 'paid',
         ]);
            
            //REPEAT
            Students::create([
            'Parent_id' => '30',
            'Class_id' => '3',
            'Staff_id' => '1',
            'FullName' => 'DAHLIA BINTI ZAKIR',
            'birthCertificateNO' => 'IJ98675',
            'MyKid' => '201506-05-4321',
            'Address1' => 'No. 5, Jalan Ceria',
            'Address2' => 'Taman Ceria',
            'Poscode' => '81200',
            'City' => 'Johor Bahru',
            'State' => 'Johor',
            'DOB' => '2015-10-20',
            'Sex' => 'Perempuan',
            'PhoneNo' => '011-98765432',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '3',
            'AnakKe' => '1',
            'SchoolName' => 'SK Taman Seri',
            'Status' => 'Active',
            'LastPaymentDate' => '2023-04-08',
            'ParentFullName' => 'ZAKIR BIN KHAIRUL',
            'ParentICno' => '800710-03-1234',
            'ParentAddress1' => 'No. 5, Jalan Ceria',
            'ParentAddress2' => 'Taman Ceria',
            'ParentPoscode' => '81200',
            'ParentCity' => 'Johor Bahru',
            'ParentState' => 'Johor',
            'ParentPhoneNo' => '019-8765432',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Juruteknik',
            'ParentIncome' => '3800.00',
            'OfficeAddress1' => 'No. 7, Jalan Bakti',
            'OfficeAddress2' => 'Taman Bakti',
            'OfficePoscode' => '81100',
            'OfficeCity' => 'Johor Bahru',
            'OfficeState' => 'Johor',
                 'RegistrastionFee' => 'paid',
         ]);

            Students::create([
            'Parent_id' => '18',
            'Class_id' => '5',
            'Staff_id' => '2',
            'FullName' => 'LINDA BINTI AHMAD',
            'birthCertificateNO' => 'KL53698',
            'MyKid' => '201312-10-5678',
            'Address1' => 'No. 9, Jalan Harmoni',
            'Address2' => 'Taman Harmoni Indah',
            'Poscode' => '43300',
            'City' => 'Seri Kembangan',
            'State' => 'Selangor',
            'DOB' => '2013-09-15',
            'Sex' => 'Perempuan',
            'PhoneNo' => '019-7654321',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '2',
            'AnakKe' => '2',
            'SchoolName' => 'SK Taman Kajang',
            'Status' => 'Active',
            'LastPaymentDate' => '2023-02-10',
            'ParentFullName' => 'AHMAD BIN JALAL',
            'ParentICno' => '811005-07-4321',
            'ParentAddress1' => 'No. 9, Jalan Harmoni',
            'ParentAddress2' => 'Taman Harmoni Indah',
            'ParentPoscode' => '43300',
            'ParentCity' => 'Seri Kembangan',
            'ParentState' => 'Selangor',
            'ParentPhoneNo' => '019-9876543',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Pegawai Bank',
            'ParentIncome' => '5800.00',
            'OfficeAddress1' => 'No. 11, Jalan Murni',
            'OfficeAddress2' => 'Taman Murni',
            'OfficePoscode' => '43000',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
                 'RegistrastionFee' => 'paid',
         ]);

            Students::create([
            'Parent_id' => '19',
            'Class_id' => '7',
            'Staff_id' => '4',
            'FullName' => 'NURUL SYAFIQAH BINTI AHMAD',
            'birthCertificateNO' => 'AD26789',
            'MyKid' => '200905-15-9876',
            'Address1' => 'No. 18, Jalan Indah',
            'Address2' => 'Taman Indah',
            'Poscode' => '43200',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'DOB' => '2009-01-30',
            'Sex' => 'Perempuan',
            'PhoneNo' => '017-8765432',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '2',
            'AnakKe' => '1',
            'SchoolName' => 'SK Taman Kajang',
            'Status' => 'Active',
            'LastPaymentDate' => '2023-01-10',
            'ParentFullName' => 'AHMAD BIN ISMAIL',
            'ParentICno' => '800602-03-5678',
            'ParentAddress1' => 'No. 18, Jalan Indah',
            'ParentAddress2' => 'Taman Indah',
            'ParentPoscode' => '43200',
            'ParentCity' => 'Kajang',
            'ParentState' => 'Selangor',
            'ParentPhoneNo' => '019-7654321',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Pegawai Kerajaan',
            'ParentIncome' => '5000.00',
            'OfficeAddress1' => 'No. 20, Jalan Bunga Raya',
            'OfficeAddress2' => 'Taman Bunga Raya',
            'OfficePoscode' => '43000',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
                 'RegistrastionFee' => 'paid',
         ]);
            

            Students::create([
            'Parent_id' => '20',
            'Class_id' => '12',
            'Staff_id' => '2',
            'FullName' => 'TAQRIZ AIMAN BIN MAT JUMAT',
            'birthCertificateNO' => 'KL53699',
            'MyKid' => '201312-10-5679',
            'Address1' => 'No. 9, Jalan Harmoni',
            'Address2' => 'Taman Harmoni Indah',
            'Poscode' => '43300',
            'City' => 'Seri Kembangan',
            'State' => 'Selangor',
            'DOB' => '2013-09-15',
            'Sex' => 'Lelaki',
            'PhoneNo' => '019-8765432',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '2',
            'AnakKe' => '3',
            'SchoolName' => 'SK Taman Kajang',
            'Status' => 'Pending',
            'LastPaymentDate' => '2023-04-10',
            'ParentFullName' => 'MAT JUMAT BIN MAT AMIN',
            'ParentICno' => '811005-07-4321',
            'ParentAddress1' => 'No. 9, Jalan Harmoni',
            'ParentAddress2' => 'Taman Harmoni Indah',
            'ParentPoscode' => '43300',
            'ParentCity' => 'Seri Kembangan',
            'ParentState' => 'Selangor',
            'ParentPhoneNo' => '019-9876543',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Pegawai Bank',
            'ParentIncome' => '5800.00',
            'OfficeAddress1' => 'No. 11, Jalan Murni',
            'OfficeAddress2' => 'Taman Murni',
            'OfficePoscode' => '43000',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
                 'RegistrastionFee' => 'paid',
         ]);
            
            Students::create([
            'Parent_id' => '21',
            'Class_id' => '8',
            'Staff_id' => '4',
            'FullName' => 'NURUL HANISAH BINTI AHMAD',
            'birthCertificateNO' => 'AD26790',
            'MyKid' => '201001-10-9876',
            'Address1' => 'No. 18, Jalan Indah',
            'Address2' => 'Taman Indah',
            'Poscode' => '43200',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'DOB' => '2010-06-12',
            'Sex' => 'Perempuan',
            'PhoneNo' => '017-8765432',
            'Nationality' => 'Warganegara',
            'Disability' => 'None',
            'BillSibling' => '2',
            'AnakKe' => '2',
            'SchoolName' => 'SK Taman Kajang',
            'Status' => 'Active',
            'LastPaymentDate' => '2023-01-10',
            'ParentFullName' => 'AHMAD BIN ZULKEFLI',
            'ParentICno' => '800602-03-5678',
            'ParentAddress1' => 'No. 18, Jalan Indah',
            'ParentAddress2' => 'Taman Indah',
            'ParentPoscode' => '43200',
            'ParentCity' => 'Kajang',
            'ParentState' => 'Selangor',
            'ParentPhoneNo' => '019-7654321',
            'ParentNationality' => 'Warganegara',
            'ParentJob' => 'Pegawai Kerajaan',
            'ParentIncome' => '5000.00',
            'OfficeAddress1' => 'No. 20, Jalan Bunga Raya',
            'OfficeAddress2' => 'Taman Bunga Raya',
            'OfficePoscode' => '43000',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
                 'RegistrastionFee' => 'paid',
         ]);
          $this->call(learningProgressSeeder::class);
          $this->call(ParentsSeeder::class);
          $this->call(ClassSeeder::class);
          $this->call(TeacherSeeder::class);
          $this->call(StaffSeeder::class);
          $this->call(HeadmasterSeeder::class);

    }

    
}
