<?php

namespace Database\Seeders;

use App\Models\Parents;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ParentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Parents::create([
            'User_ID' => '3',
            'FullName' => 'AHMAD BIN ABDULLAH',
            'ICno' => '730101-08-8457',
            'Address1' => 'No. 52',
            'Address2' => 'Jalan Dahlia 2',
            'Poscode' => '47150',
            'City' => 'Puchong',
            'State' => 'Selangor',
            'PhoneNo' => '011-24798476',
            'Nationality' => 'Warganegara',
            'Job' => 'Berniaga',
            'Income' => '1500.00',
            'OfficeAddress1' => 'No. 52',
            'OfficeAddress2' => 'Jalan Dahlia 2',
            'OfficePoscode' => '471150',
            'OfficeCity' => 'Puchong',
            'OfficeState' => 'Selangor',
        ]);

        Parents::create([
            'User_ID' => '5',   
            'FullName' => 'MOHD ZAIN BIN MOHAMAD',
            'ICno' => '730101-08-8457',
            'Address1' => 'No. 52',
            'Address2' => 'Jalan Dahlia 2',
            'Poscode' => '47150',
            'City' => 'Puchong',
            'State' => 'Selangor',
            'PhoneNo' => '011-24798476',
            'Nationality' => 'Warganegara',
            'Job' => 'Berniaga',
            'Income' => '1500.00',
            'OfficeAddress1' => 'No. 52',
            'OfficeAddress2' => 'Jalan Dahlia 2',
            'OfficePoscode' => '471150',
            'OfficeCity' => 'Puchong',
            'OfficeState' => 'Selangor',
         ]);

         Parents::create([
            'User_ID' => '5',
            'FullName' => 'ABDUL RAZAK BIN ABDUL RAHMAN',
            'ICno' => '730101-08-8457',
            'Address1' => 'No. 52',
            'Address2' => 'Jalan Dahlia 2',
            'Poscode' => '47150',
            'City' => 'Puchong',
            'State' => 'Selangor',
            'PhoneNo' => '011-24798476',
            'Nationality' => 'Warganegara',
            'Job' => 'Berniaga',
            'Income' => '1500.00',
            'OfficeAddress1' => 'No. 52',
            'OfficeAddress2' => 'Jalan Dahlia 2',
            'OfficePoscode' => '471150',
            'OfficeCity' => 'Puchong',
            'OfficeState' => 'Selangor',
         ]);

         Parents::create([
            'User_ID' => '17',
            'FullName' => 'MUHAMAD BIN ISMAIL',
            'ICno' => '730101-08-8457',
            'Address1' => 'No. 52',
            'Address2' => 'Jalan Dahlia 2',
            'Poscode' => '47150',
            'City' => 'Puchong',
            'State' => 'Selangor',
            'PhoneNo' => '011-24798476',
            'Nationality' => 'Warganegara',
            'Job' => 'Berniaga',
            'Income' => '1500.00',
            'OfficeAddress1' => 'No. 52',
            'OfficeAddress2' => 'Jalan Dahlia 2',
            'OfficePoscode' => '471150',
            'OfficeCity' => 'Puchong',
            'OfficeState' => 'Selangor',
         ]);

         Parents::create([
            'User_ID' => '16',
            'FullName' => 'MOHD FAISAL BIN MOHD AZMAN',
            'ICno' => '730101-08-8457',
            'Address1' => 'No. 52',
            'Address2' => 'Jalan Dahlia 2',
            'Poscode' => '47150',
            'City' => 'Puchong',
            'State' => 'Selangor',
            'PhoneNo' => '011-24798476',
            'Nationality' => 'Warganegara',
            'Job' => 'Berniaga',
            'Income' => '1500.00',
            'OfficeAddress1' => 'No. 52',
            'OfficeAddress2' => 'Jalan Dahlia 2',
            'OfficePoscode' => '471150',
            'OfficeCity' => 'Puchong',
            'OfficeState' => 'Selangor',
         ]);

         Parents::create([
            'User_ID' => '15',
            'FullName' => 'AZMAN BIN HAMID',
            'ICno' => '730101-08-8457',
            'Address1' => 'No. 52',
            'Address2' => 'Jalan Dahlia 2',
            'Poscode' => '47150',
            'City' => 'Puchong',
            'State' => 'Selangor',
            'PhoneNo' => '011-24798476',
            'Nationality' => 'Warganegara',
            'Job' => 'Berniaga',
            'Income' => '1500.00',
            'OfficeAddress1' => 'No. 52',
            'OfficeAddress2' => 'Jalan Dahlia 2',
            'OfficePoscode' => '471150',
            'OfficeCity' => 'Puchong',
            'OfficeState' => 'Selangor',
         ]);
 
         Parents::create([
            'User_ID' => '14', 
            'FullName' => 'ABDUL HAKIM BIN MOHD YUSOF',
             'ICno' => '730101-08-8457',
             'Address1' => 'No. 52',
             'Address2' => 'Jalan Dahlia 2',
             'Poscode' => '47150',
             'City' => 'Puchong',
             'State' => 'Selangor',
             'PhoneNo' => '011-24798476',
             'Nationality' => 'Warganegara',
             'Job' => 'Berniaga',
             'Income' => '1500.00',
             'OfficeAddress1' => 'No. 52',
             'OfficeAddress2' => 'Jalan Dahlia 2',
             'OfficePoscode' => '471150',
             'OfficeCity' => 'Puchong',
             'OfficeState' => 'Selangor',
          ]);
 
          Parents::create([
            'User_ID' => '13', 
            'FullName' => 'MOHD AMIR BIN ISKANDAR',
             'ICno' => '730101-08-8457',
             'Address1' => 'No. 52',
             'Address2' => 'Jalan Dahlia 2',
             'Poscode' => '47150',
             'City' => 'Puchong',
             'State' => 'Selangor',
             'PhoneNo' => '011-24798476',
             'Nationality' => 'Warganegara',
             'Job' => 'Berniaga',
             'Income' => '1500.00',
             'OfficeAddress1' => 'No. 52',
             'OfficeAddress2' => 'Jalan Dahlia 2',
             'OfficePoscode' => '471150',
             'OfficeCity' => 'Puchong',
             'OfficeState' => 'Selangor',
          ]);
 
          Parents::create([
            'User_ID' => '12', 
            'FullName' => 'MOHD FIRDAUS BIN AHMAD',
             'ICno' => '730101-08-8457',
             'Address1' => 'No. 52',
             'Address2' => 'Jalan Dahlia 2',
             'Poscode' => '47150',
             'City' => 'Puchong',
             'State' => 'Selangor',
             'PhoneNo' => '011-24798476',
             'Nationality' => 'Warganegara',
             'Job' => 'Berniaga',
             'Income' => '1500.00',
             'OfficeAddress1' => 'No. 52',
             'OfficeAddress2' => 'Jalan Dahlia 2',
             'OfficePoscode' => '471150',
             'OfficeCity' => 'Puchong',
             'OfficeState' => 'Selangor',
          ]);
 
          Parents::create([
            'User_ID' => '8', 
            'FullName' => 'MOHD SYAFIQ BIN IBRAHIM',
             'ICno' => '730101-08-8457',
             'Address1' => 'No. 52',
             'Address2' => 'Jalan Dahlia 2',
             'Poscode' => '47150',
             'City' => 'Puchong',
             'State' => 'Selangor',
             'PhoneNo' => '011-24798476',
             'Nationality' => 'Warganegara',
             'Job' => 'Berniaga',
             'Income' => '1500.00',
             'OfficeAddress1' => 'No. 52',
             'OfficeAddress2' => 'Jalan Dahlia 2',
             'OfficePoscode' => '471150',
             'OfficeCity' => 'Puchong',
             'OfficeState' => 'Selangor',
          ]);

          Parents::create([
            'User_ID' => '9',
            'FullName' => 'ISMAIL BIN MOHAMAD RAZALI',
            'ICno' => '730101-08-8457',
            'Address1' => 'No. 52',
            'Address2' => 'Jalan Dahlia 2',
            'Poscode' => '47150',
            'City' => 'Puchong',
            'State' => 'Selangor',
            'PhoneNo' => '011-24798476',
            'Nationality' => 'Warganegara',
            'Job' => 'Berniaga',
            'Income' => '1500.00',
            'OfficeAddress1' => 'No. 52',
            'OfficeAddress2' => 'Jalan Dahlia 2',
            'OfficePoscode' => '471150',
            'OfficeCity' => 'Puchong',
            'OfficeState' => 'Selangor',
         ]);
 
         Parents::create([
            'User_ID' => '7', 
            'FullName' => 'MOHD AMIN BIN ABDUL LATIF',
             'ICno' => '730101-08-8457',
             'Address1' => 'No. 52',
             'Address2' => 'Jalan Dahlia 2',
             'Poscode' => '47150',
             'City' => 'Puchong',
             'State' => 'Selangor',
             'PhoneNo' => '011-24798476',
             'Nationality' => 'Warganegara',
             'Job' => 'Berniaga',
             'Income' => '1500.00',
             'OfficeAddress1' => 'No. 52',
             'OfficeAddress2' => 'Jalan Dahlia 2',
             'OfficePoscode' => '471150',
             'OfficeCity' => 'Puchong',
             'OfficeState' => 'Selangor',
          ]);
 
          Parents::create([
            'User_ID' => '10', 
            'FullName' => 'HAFIZ BIN ZULKIFLI',
             'ICno' => '730101-08-8457',
             'Address1' => 'No. 52',
             'Address2' => 'Jalan Dahlia 2',
             'Poscode' => '47150',
             'City' => 'Puchong',
             'State' => 'Selangor',
             'PhoneNo' => '011-24798476',
             'Nationality' => 'Warganegara',
             'Job' => 'Berniaga',
             'Income' => '1500.00',
             'OfficeAddress1' => 'No. 52',
             'OfficeAddress2' => 'Jalan Dahlia 2',
             'OfficePoscode' => '471150',
             'OfficeCity' => 'Puchong',
             'OfficeState' => 'Selangor',
          ]);
 
          Parents::create([
            'User_ID' => '6', 
            'FullName' => 'MOHD DANISH BIN MOHD YUSOFF',
             'ICno' => '730101-08-8457',
             'Address1' => 'No. 52',
             'Address2' => 'Jalan Dahlia 2',
             'Poscode' => '47150',
             'City' => 'Puchong',
             'State' => 'Selangor',
             'PhoneNo' => '011-24798476',
             'Nationality' => 'Warganegara',
             'Job' => 'Berniaga',
             'Income' => '1500.00',
             'OfficeAddress1' => 'No. 52',
             'OfficeAddress2' => 'Jalan Dahlia 2',
             'OfficePoscode' => '471150',
             'OfficeCity' => 'Puchong',
             'OfficeState' => 'Selangor',
          ]);
 
          Parents::create([
            'User_ID' => '11', 
            'FullName' => 'MOHD RAZALI BIN ABDUL RAHMAN',
             'ICno' => '730101-08-8457',
             'Address1' => 'No. 52',
             'Address2' => 'Jalan Dahlia 2',
             'Poscode' => '47150',
             'City' => 'Puchong',
             'State' => 'Selangor',
             'PhoneNo' => '011-24798476',
             'Nationality' => 'Warganegara',
             'Job' => 'Berniaga',
             'Income' => '1500.00',
             'OfficeAddress1' => 'No. 52',
             'OfficeAddress2' => 'Jalan Dahlia 2',
             'OfficePoscode' => '471150',
             'OfficeCity' => 'Puchong',
             'OfficeState' => 'Selangor',
          ]);

          Parents::create([
            'User_ID' => '42', 
            'FullName' => 'ABDULLAH BIN MOHAMMAD',
            'ICno' => '760501-07-8901',
            'Address1' => 'No. 8, Jalan Harmoni',
            'Address2' => 'Taman Seri Harmoni',
            'Poscode' => '43200',
            'City' => 'Cheras',
            'State' => 'Selangor',
            'PhoneNo' => '019-8765432',
            'Nationality' => 'Warganegara',
            'Job' => 'Kakitangan Kerajaan',
            'Income' => '5000.00',
            'OfficeAddress1' => 'No. 18, Jalan Anggerik',
            'OfficeAddress2' => 'Taman Anggerik',
            'OfficePoscode' => '43020',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
          ]);

          Parents::create([
            'User_ID' => '41', 
            'FullName' => 'MOHD RAZALI BIN ABDUL RAHMAN',
            'ICno' => '880301-03-5678',
            'Address1' => 'No. 21, Jalan Delima',
            'Address2' => 'Taman Seri Delima',
            'Poscode' => '83000',
            'City' => 'Batu Pahat',
            'State' => 'Johor',
            'PhoneNo' => '011-24798476',
            'Nationality' => 'Warganegara',
            'Job' => 'Berniaga',
            'Income' => '1500.00',
            'OfficeAddress1' => 'No. 25, Jalan Cempaka',
            'OfficeAddress2' => 'Taman Cempaka',
            'OfficePoscode' => '43000',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
          ]);

          Parents::create([
            'User_ID' => '40', 
            'FullName' => 'AHMAD BIN JALAL',
            'ICno' => '811005-07-4321',
            'Address1' => 'No. 9, Jalan Harmoni',
            'Address2' => 'Taman Harmoni Indah',
            'Poscode' => '43300',
            'City' => 'Seri Kembangan',
            'State' => 'Selangor',
            'PhoneNo' => '019-9876543',
            'Nationality' => 'Warganegara',
            'Job' => 'Pegawai Bank',
            'Income' => '5800.00',
            'OfficeAddress1' => 'No. 11, Jalan Murni',
            'OfficeAddress2' => 'Taman Murni',
            'OfficePoscode' => '43000',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
          ]);

          //19
          Parents::create([
            'User_ID' => '39', 
            'FullName' => 'AHMAD BIN ISMAIL',
            'ICno' => '800602-03-5678',
            'Address1' => 'No. 18, Jalan Indah',
            'Address2' => 'Taman Indah',
            'Poscode' => '43200',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'PhoneNo' => '019-7654321',
            'Nationality' => 'Warganegara',
            'Job' => 'Pegawai Kerajaan',
            'Income' => '5000.00',
            'OfficeAddress1' => 'No. 20, Jalan Bunga Raya',
            'OfficeAddress2' => 'Taman Bunga Raya',
            'OfficePoscode' => '43000',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
          ]);

          //20
          Parents::create([
            'User_ID' => '38', 
            'FullName' => 'MAT JUMAT BIN MAT AMIN',
            'ICno' => '811005-07-4321',
            'Address1' => 'No. 9, Jalan Harmoni',
            'Address2' => 'Taman Harmoni Indah',
            'Poscode' => '43300',
            'City' => 'Seri Kembangan',
            'State' => 'Selangor',
            'PhoneNo' => '019-9876543',
            'Nationality' => 'Warganegara',
            'Job' => 'Pegawai Bank',
            'Income' => '5800.00',
            'OfficeAddress1' => 'No. 11, Jalan Murni',
            'OfficeAddress2' => 'Taman Murni',
            'OfficePoscode' => '43000',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
          ]);

          //21
          Parents::create([
            'User_ID' => '37', 
            'FullName' => 'AHMAD BIN ZULKEFLI',
            'ICno' => '800602-03-5678',
            'Address1' => 'No. 18, Jalan Indah',
            'Address2' => 'Taman Indah',
            'Poscode' => '43200',
            'City' => 'Kajang',
            'State' => 'Selangor',
            'PhoneNo' => '019-7654321',
            'Nationality' => 'Warganegara',
            'Job' => 'Pegawai Kerajaan',
            'Income' => '5000.00',
            'OfficeAddress1' => 'No. 20, Jalan Bunga Raya',
            'OfficeAddress2' => 'Taman Bunga Raya',
            'OfficePoscode' => '43000',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
          ]);

          //22
          Parents::create([
            'User_ID' => '36', 
            'FullName' => 'AHMAD BIN JAMALUDIN',
            'ICno' => '820612-05-4321',
            'Address1' => 'No. 14, Jalan Megah',
            'Address2' => 'Taman Megah Indah',
            'Poscode' => '75400',
            'City' => 'Melaka',
            'State' => 'Melaka',
            'PhoneNo' => '016-8765432',
            'Nationality' => 'Warganegara',
            'Job' => 'Juruteknik',
            'Income' => '3500.00',
            'OfficeAddress1' => 'No. 20, Jalan Bunga Raya',
            'OfficeAddress2' => 'Taman Bunga Raya',
            'OfficePoscode' => '75000',
            'OfficeCity' => 'Melaka',
            'OfficeState' => 'Melaka',
          ]);

          //23
          Parents::create([
            'User_ID' => '35', 
            'FullName' => 'HELMI BIN HAIRUL',
            'ICno' => '840501-07-1234',
            'Address1' => 'No. 3, Jalan Bahagia',
            'Address2' => 'Taman Bahagia',
            'Poscode' => '56000',
            'City' => 'Kuala Lumpur',
            'State' => 'Wilayah Persekutuan',
            'PhoneNo' => '019-9876543',
            'Nationality' => 'Warganegara',
            'Job' => 'Pegawai Kerajaan',
            'Income' => '6000.00',
            'OfficeAddress1' => 'No. 5, Jalan Angsana',
            'OfficeAddress2' => 'Taman Angsana',
            'OfficePoscode' => '56100',
            'OfficeCity' => 'Kuala Lumpur',
            'OfficeState' => 'Wilayah Persekutuan',
          ]);

          //24
          Parents::create([
            'User_ID' => '34', 
            'FullName' => 'ABDUL RAHIM BIN HASHIM',
            'ICno' => '850701-03-4567',
            'Address1' => 'No. 12, Jalan Bestari',
            'Address2' => 'Taman Bestari',
            'Poscode' => '43300',
            'City' => 'Seri Kembangan',
            'State' => 'Selangor',
            'PhoneNo' => '012-3456789',
            'Nationality' => 'Warganegara',
            'Job' => 'Pengurus Perniagaan',
            'Income' => '4500.00',
            'OfficeAddress1' => 'No. 15, Jalan Mawar',
            'OfficeAddress2' => 'Taman Mawar',
            'OfficePoscode' => '43200',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
          ]);

          //25
          Parents::create([
            'User_ID' => '33', 
            'FullName' => 'WAN AIMAN BIN WAN ZOL',
            'ICno' => '800710-03-1234',
            'Address1' => 'No. 5, Jalan Ceria',
            'Address2' => 'Taman Ceria',
            'Poscode' => '81200',
            'City' => 'Johor Bahru',
            'State' => 'Johor',
            'PhoneNo' => '019-8765432',
            'Nationality' => 'Warganegara',
            'Job' => 'Juruteknik',
            'Income' => '3800.00',
            'OfficeAddress1' => 'No. 7, Jalan Bakti',
            'OfficeAddress2' => 'Taman Bakti',
            'OfficePoscode' => '81100',
            'OfficeCity' => 'Johor Bahru',
            'OfficeState' => 'Johor',
          ]);

          //26
          Parents::create([
            'User_ID' => '32', 
            'FullName' => 'AMIN BIN AMAN',
            'ICno' => '811005-07-4321',
            'Address1' => 'No. 9, Jalan Harmoni',
            'Address2' => 'Taman Harmoni Indah',
            'Poscode' => '43300',
            'City' => 'Seri Kembangan',
            'State' => 'Selangor',
            'PhoneNo' => '019-9876543',
            'Nationality' => 'Warganegara',
            'Job' => 'Pegawai Bank',
            'Income' => '5800.00',
            'OfficeAddress1' => 'No. 11, Jalan Murni',
            'OfficeAddress2' => 'Taman Murni',
            'OfficePoscode' => '43000',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
          ]);

          //27
          Parents::create([
            'User_ID' => '31', 
            'FullName' => 'ZIZAN BIN AMRAN',
            'ICno' => '811005-07-4321',
            'Address1' => 'No. 9, Jalan Harmoni',
            'Address2' => 'Taman Harmoni Indah',
            'Poscode' => '43300',
            'City' => 'Seri Kembangan',
            'State' => 'Selangor',
            'PhoneNo' => '019-9876543',
            'Nationality' => 'Warganegara',
            'Job' => 'Pegawai Bank',
            'Income' => '5800.00',
            'OfficeAddress1' => 'No. 11, Jalan Murni',
            'OfficeAddress2' => 'Taman Murni',
            'OfficePoscode' => '43000',
            'OfficeCity' => 'Kajang',
            'OfficeState' => 'Selangor',
          ]);

          //28
          Parents::create([
            'User_ID' => '30', 
            'FullName' => 'ISMAIL BIN HASHIM',
            'ICno' => '860602-03-4567',
            'Address1' => 'No. 2, Jalan Anggerik',
            'Address2' => 'Taman Anggerik',
            'Poscode' => '81200',
            'City' => 'Johor Bahru',
            'State' => 'Johor',
            'PhoneNo' => '012-3456789',
            'Nationality' => 'Warganegara',
            'Job' => 'Pegawai Kerajaan',
            'Income' => '4800.00',
            'OfficeAddress1' => 'No. 4, Jalan Mawar',
            'OfficeAddress2' => 'Taman Mawar',
            'OfficePoscode' => '81100',
            'OfficeCity' => 'Johor Bahru',
            'OfficeState' => 'Johor',
          ]);

          Parents::create([
            'User_ID' => '29', 
            'FullName' => 'NIK MAT BIN NIK AZIZ',
            'ICno' => '790821-08-4321',
            'Address1' => 'No. 7, Jalan Seri Baiduri',
            'Address2' => 'Taman Seri Baiduri',
            'Poscode' => '83020',
            'City' => 'Johor Bahru',
            'State' => 'Johor',
            'PhoneNo' => '019-7654321',
            'Nationality' => 'Warganegara',
            'Job' => 'Pegawai Bank',
            'Income' => '8000.00',
            'OfficeAddress1' => 'No. 10, Jalan Indah',
            'OfficeAddress2' => 'Taman Indah',
            'OfficePoscode' => '83000',
            'OfficeCity' => 'Johor Bahru',
            'OfficeState' => 'Johor',
          ]);

          Parents::create([
            'User_ID' => '28', 
            'FullName' => 'ZAKIR BIN KHAIRUL',
            'ICno' => '800710-03-1234',
            'Address1' => 'No. 5, Jalan Ceria',
            'Address2' => 'Taman Ceria',
            'Poscode' => '81200',
            'City' => 'Johor Bahru',
            'State' => 'Johor',
            'PhoneNo' => '019-8765432',
            'Nationality' => 'Warganegara',
            'Job' => 'Juruteknik',
            'Income' => '3800.00',
            'OfficeAddress1' => 'No. 7, Jalan Bakti',
            'OfficeAddress2' => 'Taman Bakti',
            'OfficePoscode' => '81100',
            'OfficeCity' => 'Johor Bahru',
            'OfficeState' => 'Johor',
          ]);
    }
}
